// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV61ht6cf8l4GALj578jBcl-FnFTHBDkM',
    appId: '1:832623302445:web:f3686ebb18c017e183e5a4',
    messagingSenderId: '832623302445',
    projectId: 'character-rpg',
    authDomain: 'character-rpg.firebaseapp.com',
    storageBucket: 'character-rpg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEtJC1d548tZu6WUKst1tHLcok8Ui8ra0',
    appId: '1:832623302445:android:c7fc19403e1b539783e5a4',
    messagingSenderId: '832623302445',
    projectId: 'character-rpg',
    storageBucket: 'character-rpg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_u4HWWSTWSB-Agep3mDAJ8fM7fyqeJJ4',
    appId: '1:832623302445:ios:0de56fafe520b5ff83e5a4',
    messagingSenderId: '832623302445',
    projectId: 'character-rpg',
    storageBucket: 'character-rpg.appspot.com',
    iosBundleId: 'com.example.crpg',
  );
}
